# mpesa_config.toml
# DO NOT COMMIT TO GIT! Add to .gitignore

[mpesa.daraja]
consumer_key    = "4BcIP7LtB5oLjnwewHP6MOABGGd2AjDcQJc0NFbnPAyJhG5T"
consumer_secret = "7mk1O3sqHx69QETjAbEGLdZXrVJywvwazlMtK8k5wbP4cpWyfOJdssgsH6Uxzw4r"
shortcode       = "174379"
passkey         = "FW2zvrB+nE2W9Mg09kmeLK3+TtckDyGXOHrpfPxMh2apyoIMSMM2uj4koM7X+a8zjjCudwVZx0n6NW3t58O3Hev537EvzvpooT7wvGyEKnTG9sQ275KlDkRWRdL/bv9ypBG+eY5zHUipTkTDegk4HEh8qQKXmN3CzGchrNEI4Yxl7TKpgY1HQXbZrDX0YnwEunvp282hxoyz6/NIgCSwaBJD4+0AIczB24KcaGF4zOScW0EBxXT1BZx7uYWgh2p1ah+mF5dlkR5TnrnDvuAH53GNOZceCRIEq8qQyDcXkDVSMfKnFfGHDXUFJFfgoLEs0QSMO8GfWL19yCqVrhW4eA=="
callback_url    = "https://your-app-url.ngrok.io/callback"  # UPDATE THIS